# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hyde
tagline:          'theme'
description:      ''
url:              http://github.com/vladimirmezera
baseurl:          /

author:
  name:           'Vladimir Mezera'
  url:            https://twitter.com/vladimirmezera

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vladimirmezera
